# Generated by Django 6.1 on 2026-09-14 10:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('school', 'School'), ('regional', 'Regional'), ('national', 'National'), ('international', 'International')], default='school', max_length=20)),
                ('date_achieved', models.DateField()),
                ('certificate_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
