# Generated by Django 6.1 on 2026-10-05 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_achievement_starred_by_experience_starred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
